### PR TITLE
docs(global): 📝  Fix license badge

### PR DESCRIPTION
**Pull request by rahulkarda**
Signed-off-by: Rahul Karda <rahulkarda2002@gmail.com>

## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- The license badge is now showing properly
- GPL v3 license was added
- Nothing else was changed

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by JoeKarow** [comment]
Closes #24

**Review by JoeKarow — APPROVED** [review]
Thanks for catching this!

Thank you!

**Comment by rahulkarda** [comment]
> Thanks for catching this!
> 
> Thank you! [ ](https://camo.githubusercontent.com/cf8ccfa3f10769ccdbd37813f63e2df01eda2da4cc914c62b07e2d41cebec349/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3236444f4d656144326764474534344c4b2f67697068792e676966) Thank you! [ ](https://camo.githubusercontent.com/cf8ccfa3f10769ccdbd37813f63e2df01eda2da4cc914c62b07e2d41cebec349/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3236444f4d656144326764474534344c4b2f67697068792e676966)

haha np

**Comment by rahulkarda** [comment]
haha np

**Pull request merged**
